### ISSUE TITLE
IllegalArgumentException when adding new note attachment

### ISSUE THREAD

**Issue by Zaxim** [avram/zandy#131]
# Description

Adding a new note to an existing library item results in Zandy force closing.  I believe it's because of a a parameter being set to null in the SQL query.
# Repro Steps
1. Click on a library item
2. Click on attachments
3. Press the plus button
4. Type something into the note dialog box
5. Press "Ok button"
6. Error dialog pops up, "Unfortunately, Zandy has stopped
## Expected Outcome

The note gets added to the zotero library
## Actual Outcome

Zandy force closes
# Supplemental Information

`02-27 21:56:31.065    4649-4649/com.gimranov.zandy.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.gimranov.zandy.app, PID: 4649
    java.lang.IllegalArgumentException: the bind value at index 1 is null
            at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
            at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
            at com.gimranov.zandy.app.data.Database.query(Database.java:57)
            at com.gimranov.zandy.app.data.Attachment.load(Attachment.java:223)
            at com.gimranov.zandy.app.AttachmentActivity$9.onClick(AttachmentActivity.java:350)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:160)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
`

**Comment by Zaxim** [comment]
I've identified that the issue occurs due to a null pointer in AttachmentActivity.java 

In fact, because we declare a new local Bundle [here](https://github.com/avram/zandy/blob/master/src/main/java/com/gimranov/zandy/app/AttachmentActivity.java) when we set the `itemKey` and `mode` [here](https://github.com/avram/zandy/blob/master/src/main/java/com/gimranov/zandy/app/AttachmentActivity.java#L771-772) it's to the local variable, not the class variable.
